### ISSUE TITLE
Team label error is not clear

### ISSUE THREAD

**Issue by hoptical** [snapp-incubator/ceph-s3-operator#34]
**Documentation**

- The requirement of the ClusterResourceQuota CRD must be mentioned in the Readme and CSV description.

**Code**

- When a user applies a `S3UserClaim` object he faces this error: `The S3UserClaim "s3userclaim-sample" is invalid: spec.quota: Internal error: please contact the cloud team`. This error is related to the namespace which doesn't have the `team` label. The error should be rewritten to be more clear.

**Comment by 1995parham** [comment]
Also, I think because we are going to share it in public we need to remove references to the "cloud team".
